-- Baseline schema. Flyway owns the schema from here on; Hibernate only validates it.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE knowledge_chunk (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(255) NOT NULL,
    title_ref    VARCHAR(255),
    content      TEXT         NOT NULL,
    embedding    vector(768)  NOT NULL,
    content_hash VARCHAR(64)  NOT NULL,
    CONSTRAINT uq_knowledge_chunk_content_hash UNIQUE (content_hash)
);

-- Approximate nearest-neighbour index for cosine distance (the <=> operator).
-- Not used by the planner at small row counts; it earns its keep as the corpus grows.
CREATE INDEX idx_knowledge_chunk_embedding_hnsw
    ON knowledge_chunk USING hnsw (embedding vector_cosine_ops);
