-- Server-side chat memory: one conversation per user, so the user id *is* the conversation key
-- and there is no separate conversation table to keep in sync.
--
-- These rows are transient by design. Reads filter on created_at against app.chat-memory.ttl and
-- a scheduled job deletes what falls behind it, so this table is a rolling window of recent
-- turns, never a permanent transcript. Anything that needs to survive an hour does not belong
-- here.

CREATE TABLE conversation_turn (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(128) NOT NULL,
    role       VARCHAR(16)  NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_conversation_turn_role CHECK (role IN ('USER', 'ASSISTANT'))
);

-- Every read is "the newest N turns of one user, after a cutoff"; every delete is "everything
-- before a cutoff". Two indexes because the delete does not filter by user.
CREATE INDEX idx_conversation_turn_user_created ON conversation_turn (user_id, created_at DESC);
CREATE INDEX idx_conversation_turn_created ON conversation_turn (created_at);
