-- Accounts. Named app_user because "user" is reserved in PostgreSQL and every query touching it
-- would need quoting.
--
-- There is no email confirmation yet: registration creates a usable account immediately, so the
-- address here is *claimed*, not verified. Anything that must reach a real inbox has to wait for
-- a confirmation flow.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 254 is the maximum length of an addr-spec in practice (RFC 5321 envelope limit).
    email         VARCHAR(254) NOT NULL,
    -- BCrypt encodes to 60 characters; the extra room is so switching algorithm (argon2id
    -- encodes to ~96) does not need a migration to widen the column mid-incident.
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Uniqueness is only as good as the normalisation in EmailAddress: the address is lowercased
    -- and trimmed before it ever reaches this table, so "A@b.com" and "a@b.com " collide here.
    CONSTRAINT uq_app_user_email UNIQUE (email)
);
