-- Login sessions. The token itself is never stored: the client holds a random opaque string and
-- this table holds its SHA-256, so a dump of this table does not hand anyone a usable session.
-- (The token is 256 bits of SecureRandom output, not a password, so a plain hash is the right
-- tool here — there is nothing to brute-force.)
--
-- Sessions expire by timestamp and are deleted by a scheduled purge, exactly like conversation
-- turns: authentication filters on expires_at at lookup time, so an expired session is dead
-- whether or not the purge has run.

CREATE TABLE user_session (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    user_id    BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_user_session_token_hash UNIQUE (token_hash)
);

-- Every authenticated request is one lookup by token_hash (served by the unique constraint).
-- The other two serve the purge and "log this account out everywhere".
CREATE INDEX idx_user_session_expires ON user_session (expires_at);
CREATE INDEX idx_user_session_user ON user_session (user_id);
