package com.seuprojeto.backend.service;

import com.seuprojeto.backend.config.AuthProperties;
import com.seuprojeto.backend.dto.AuthResponse;
import com.seuprojeto.backend.dto.LoginRequest;
import com.seuprojeto.backend.dto.RegisterRequest;
import com.seuprojeto.backend.error.EmailAlreadyRegisteredException;
import com.seuprojeto.backend.error.InvalidCredentialsException;
import com.seuprojeto.backend.model.AppUser;
import com.seuprojeto.backend.model.AuthenticatedUser;
import com.seuprojeto.backend.model.UserSession;
import com.seuprojeto.backend.repository.AppUserRepository;
import com.seuprojeto.backend.repository.UserSessionRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class AuthServiceTest {

    private static final Instant NOW = Instant.parse("2026-08-19T12:00:00Z");
    private static final Duration TTL = Duration.ofHours(24);
    private static final String PASSWORD = "senha-bem-boa";

    private AppUserRepository users;
    private UserSessionRepository sessions;
    private PasswordEncoder passwordEncoder;
    private AuthService service;

    /**
     * An account whose stored hash really is {@link #PASSWORD}, hashed by the real encoder.
     *
     * <p>Mocked rather than constructed because the id is generated by the database and these
     * tests assert on it, and built here rather than inside a {@code thenReturn(...)} because
     * Mockito refuses to stub one mock while another stubbing is still open.
     */
    private AppUser existingUser;

    @BeforeEach
    void setUp() {
        users = mock(AppUserRepository.class);
        sessions = mock(UserSessionRepository.class);
        // The real hasher: the point of most of these tests is what happens to the password.
        passwordEncoder = new BCryptPasswordEncoder(10);
        service = new AuthService(users, sessions, passwordEncoder,
                new AuthProperties(TTL, 10, Duration.ofHours(1)),
                Clock.fixed(NOW, ZoneOffset.UTC));
        when(users.save(any())).thenAnswer(invocation -> invocation.getArgument(0));

        existingUser = mock(AppUser.class);
        when(existingUser.getId()).thenReturn(7L);
        when(existingUser.getEmail()).thenReturn("pedro@usp.br");
        when(existingUser.getPasswordHash()).thenReturn(passwordEncoder.encode(PASSWORD));
    }

    @Test
    void register_newAddress_storesAHashAndNeverThePassword() {
        when(users.findByEmail("pedro@usp.br")).thenReturn(Optional.empty());

        service.register(new RegisterRequest("Pedro@USP.br", PASSWORD));

        ArgumentCaptor<AppUser> saved = ArgumentCaptor.forClass(AppUser.class);
        verify(users).save(saved.capture());
        assertThat(saved.getValue().getEmail()).isEqualTo("pedro@usp.br");
        assertThat(saved.getValue().getPasswordHash())
                .isNotEqualTo(PASSWORD)
                .startsWith("$2");
        assertThat(passwordEncoder.matches(PASSWORD, saved.getValue().getPasswordHash())).isTrue();
    }

    @Test
    void register_returnsATokenAndItsExpiry() {
        when(users.findByEmail(anyString())).thenReturn(Optional.empty());

        AuthResponse response = service.register(new RegisterRequest("pedro@usp.br", PASSWORD));

        assertThat(response.token()).isNotBlank();
        assertThat(response.expiresAt()).isEqualTo(NOW.plus(TTL));
        assertThat(response.email()).isEqualTo("pedro@usp.br");
    }

    @Test
    void register_storesOnlyTheHashOfTheToken_soADumpOfTheTableIsUseless() {
        when(users.findByEmail(anyString())).thenReturn(Optional.empty());

        AuthResponse response = service.register(new RegisterRequest("pedro@usp.br", PASSWORD));

        ArgumentCaptor<UserSession> session = ArgumentCaptor.forClass(UserSession.class);
        verify(sessions).save(session.capture());
        assertThat(session.getValue().getTokenHash())
                .isNotEqualTo(response.token())
                .hasSize(UserSession.TOKEN_HASH_LENGTH);
        assertThat(session.getValue().getExpiresAt()).isEqualTo(NOW.plus(TTL));
    }

    @Test
    void register_addressAlreadyTaken_isRejected() {
        when(users.findByEmail("pedro@usp.br")).thenReturn(Optional.of(existingUser));

        assertThatExceptionOfType(EmailAlreadyRegisteredException.class)
                .isThrownBy(() -> service.register(new RegisterRequest("pedro@usp.br", PASSWORD)));

        verify(users, never()).save(any());
    }

    @Test
    void register_losesTheRaceToAConcurrentRegistration_stillReportsAConflict() {
        // findByEmail is a read, so two registrations of the same address both pass the check and
        // meet at the unique constraint. Same answer either way.
        when(users.findByEmail(anyString())).thenReturn(Optional.empty());
        when(users.save(any())).thenThrow(new DataIntegrityViolationException("uq_app_user_email"));

        assertThatExceptionOfType(EmailAlreadyRegisteredException.class)
                .isThrownBy(() -> service.register(new RegisterRequest("pedro@usp.br", PASSWORD)));
    }

    @Test
    void register_weakPassword_isRejectedBeforeAnythingIsStored() {
        when(users.findByEmail(anyString())).thenReturn(Optional.empty());

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> service.register(new RegisterRequest("pedro@usp.br", "curta")));

        verify(users, never()).save(any());
        verify(sessions, never()).save(any());
    }

    @Test
    void register_malformedAddress_isRejected() {
        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> service.register(new RegisterRequest("sem-arroba", PASSWORD)));
    }

    @Test
    void login_correctPassword_opensASession() {
        when(users.findByEmail("pedro@usp.br")).thenReturn(Optional.of(existingUser));

        AuthResponse response = service.login(new LoginRequest("  Pedro@USP.br ", PASSWORD));

        assertThat(response.token()).isNotBlank();
        verify(sessions).save(any());
    }

    @Test
    void login_wrongPassword_isRefusedWithoutSayingWhy() {
        when(users.findByEmail(anyString())).thenReturn(Optional.of(existingUser));

        assertThatExceptionOfType(InvalidCredentialsException.class)
                .isThrownBy(() -> service.login(new LoginRequest("pedro@usp.br", "outra-senha")))
                .withMessage("E-mail ou senha inválidos");

        verify(sessions, never()).save(any());
    }

    @Test
    void login_unknownAddress_isRefusedWithTheSameMessageAsAWrongPassword() {
        // Identical message: the response must not reveal whether an address has an account.
        when(users.findByEmail(anyString())).thenReturn(Optional.empty());

        assertThatExceptionOfType(InvalidCredentialsException.class)
                .isThrownBy(() -> service.login(new LoginRequest("ninguem@usp.br", PASSWORD)))
                .withMessage("E-mail ou senha inválidos");
    }

    @Test
    void login_malformedAddress_isRefusedAsCredentialsNotAsValidation() {
        assertThatExceptionOfType(InvalidCredentialsException.class)
                .isThrownBy(() -> service.login(new LoginRequest("sem-arroba", PASSWORD)));
    }

    @Test
    void authenticate_validToken_resolvesTheAccount() {
        AuthResponse response = openSession();
        ArgumentCaptor<UserSession> stored = ArgumentCaptor.forClass(UserSession.class);
        verify(sessions).save(stored.capture());
        when(sessions.findValid(stored.getValue().getTokenHash(), NOW))
                .thenReturn(Optional.of(stored.getValue()));
        when(users.findById(7L)).thenReturn(Optional.of(existingUser));

        Optional<AuthenticatedUser> user = service.authenticate(response.token());

        assertThat(user).contains(new AuthenticatedUser(7L, "pedro@usp.br"));
    }

    @Test
    void authenticate_unknownOrExpiredToken_isEmptyNotAnException() {
        when(sessions.findValid(anyString(), any())).thenReturn(Optional.empty());

        assertThat(service.authenticate("nao-existe")).isEmpty();
    }

    @Test
    void authenticate_noToken_isEmptyAndTouchesNoDatabase() {
        assertThat(service.authenticate(null)).isEmpty();
        assertThat(service.authenticate("  ")).isEmpty();

        verify(sessions, never()).findValid(anyString(), any());
    }

    @Test
    void authenticate_sessionSurvivedItsAccount_isEmpty() {
        when(sessions.findValid(anyString(), any()))
                .thenReturn(Optional.of(new UserSession("hash", 7L, NOW, NOW.plus(TTL))));
        when(users.findById(anyLong())).thenReturn(Optional.empty());

        assertThat(service.authenticate("qualquer")).isEmpty();
    }

    @Test
    void logout_revokesThatSessionOnly() {
        service.logout("um-token");

        ArgumentCaptor<String> hash = ArgumentCaptor.forClass(String.class);
        verify(sessions).deleteByTokenHash(hash.capture());
        assertThat(hash.getValue()).isNotEqualTo("um-token").hasSize(UserSession.TOKEN_HASH_LENGTH);
    }

    @Test
    void logout_withoutAToken_isANoOp() {
        service.logout(null);
        service.logout("   ");

        verify(sessions, never()).deleteByTokenHash(anyString());
    }

    @Test
    void purgeExpiredSessions_deletesEverythingPastItsExpiry() {
        when(sessions.deleteExpired(NOW)).thenReturn(3);

        assertThat(service.purgeExpiredSessions()).isEqualTo(3);
        verify(sessions).deleteExpired(NOW);
    }

    private AuthResponse openSession() {
        when(users.findByEmail(anyString())).thenReturn(Optional.of(existingUser));
        return service.login(new LoginRequest("pedro@usp.br", PASSWORD));
    }

}
